### ISSUE TITLE
Any way to start from a specific page?

### ISSUE THREAD

**Issue by tamarw** [recoilme/unsplash_dwn#1]
Hi! This works well, but I get 403 errors between pages 80-95 and I'm thinking it's beause I'm hitting an API limitation. Is there any way you might consider an argument input to start at a specific page so that perhaps it doesn't make an attempt to download files I already have so as not to go against the API limitation?

Great job on this. I tried about 5 scripts before I stumbled upon this one.

**Comment by recoilme** [comment]
The content on the pages varies each time, but you can continue if you have not deleted the old files, it will scan through the pages and only download the new ones. When it downloads the entire output, it crashes or freezes (about 80-95 pages).

**Comment by tamarw** [comment]
It was weird, I got 403 the first time at page 95, then at page 83, and then at page 53. Seems pretty arbitrary. I left it running overnight and it finally picked up but now some of the images aren't downloading. Any idea why it would fail to create these files? It's just running through and rerunning through page 159 now. 

2024/01/30 13:57:02 Photo  5KxA53UU6Yo.png  already downloaded.
2024/01/30 13:57:02 Photo  iDhnrrzclqk.png  already downloaded.
2024/01/30 13:57:02 Photo  SHIKDT_U7EQ.png  already downloaded.
2024/01/30 13:57:02 Photo  i_ca43piV04.png  already downloaded.
2024/01/30 13:57:02 Downloaded:  YXgOnfLl1PE
2024/01/30 13:57:02 Fail create file  YXgOnfLl1PE
2024/01/30 13:57:02 Photo  b27gdg7LPUU.png  already downloaded.
2024/01/30 13:57:02 Photo  xqLiJ_7YbFI.png  already downloaded.
2024/01/30 13:57:02 Downloaded:  CMFx0dYN2Q0
2024/01/30 13:57:02 Fail create file  CMFx0dYN2Q0
2024/01/30 13:57:02 Photo  g2BWlyejtqg.png  already downloaded.
2024/01/30 13:57:02 Photo  63uG_h39hjY.png  already downloaded.
2024/01/30 13:57:02 Downloaded:  AMkRqugSNek
2024/01/30 13:57:02 Fail create file  AMkRqugSNek
2024/01/30 13:57:02 Photo  ObhUk9MP5_g.png  already downloaded.

edit: removed code brackets because it put everything on one line

**Comment by tamarw** [comment]
Solved. Hard drive out of space, just dealing with this now. Not sure if this means I'm done with all the files or not. 

2024/01/30 16:22:45 https://api.unsplash.com/search/photos?page=201&per_page=30&query=thatsmysecret, query:  map[page:[201] per_page:[30] query:[thatsmysecret]]
2024/01/30 16:22:45 photos:  0 err:  json: cannot unmarshal object into Go value of type main.Photos
2024/01/30 16:23:15 https://api.unsplash.com/search/photos?page=201&per_page=30&query=thatsmysecret  , query:  map[page:[201] per_page:[30] query:[thatsmysecret]]
2024/01/30 16:23:15 photos:  0 err:  json: cannot unmarshal object into Go value of type main.Photos
2024/01/30 16:23:45 https://api.unsplash.com/search/photos?page=201&per_page=30&query=thatsmysecret  , query:  map[page:[201] per_page:[30] query:[thatsmysecret]]
2024/01/30 16:23:45 photos:  0 err:  json: cannot unmarshal object into Go value of type main.Photos

**Comment by recoilme** [comment]
thats ok, wrong warning - i need to hide this
